### ISSUE TITLE
Map escape to hide preview window

### ISSUE THREAD

**Issue by matthewblott** [JMarkin/nvim-tree.lua-float-preview#16]
My question is the same as the title. I sometimes want the floating window to disappear. In my current setup with AstroNvim I can do this by hitting escape but that setup uses a different file explorer. Thanks in advance :-)

EDIT

I realise to get the AstroNvim behaviour I want to toggle the float window. I tried setting `toggled_on = false` in the options but this hasn't worked, the preview window loads automatically. FWIW I just copied the default example given and I haven't changed anything.

**Comment by JMarkin** [comment]
@matthewblott in config, you can to set
```lua
mapping = {
  ...
  -- enable/disable float windows
  toggle = { "<Esc>" },
},
``` 

it toggle preview

in other cases you can attach to float preview buffer any logic, use this hook
```lua
hooks = {
  ...
  post_open = function(bufnr)
    return true
  end,
}
``` 
bufnr - standard neovim buffer number

**Comment by matthewblott** [comment]
@JMarkin thanks, you were very quick to respond while I was editing my post! Thanks I'll try your suggestion but as my update says, the default disabling doesn't appear to work. I've got a pretty vanilla setup so I'm not sure what I'm doing wrong.

**Comment by JMarkin** [comment]
@matthewblott 
May be I don't understand what you want.

If you want open preview manually you can set `toggled_on=false`. After this option, you can open preview press "mapping.toggle" key, your cursor should be on line of file on nvim-tree what you want to preview.

If you want hide preview, you can press "mapping.toggle" key.

Default key of "mapping.toggle" is ctrl+x

video example of usage, I pressed ctrl+x twice: to hide and to show
https://github.com/JMarkin/nvim-tree.lua-float-preview/assets/15740814/706b58f9-e700-45b2-ac10-f3bfdc5af13e

I checked, AstroNvim uses neo-tree on default as file explorer, did you changed it to nvim-tree.lua ?

**Comment by JMarkin** [comment]
@matthewblott Do you find a solution to the issue? Can you close it?

**Comment by matthewblott** [comment]
Not really but it's not important, go ahead and close :-)
