### ISSUE TITLE
Creating new file opens that in the NvimTree Window

### ISSUE THREAD

**Issue by semi710** [JMarkin/nvim-tree.lua-float-preview#17]
I have floating window config.
If i create a new file it just opens it inside the NvimTree window how can i prevent that from happening?

**Comment by JMarkin** [comment]
Hello, @niksingh710 
I think you should ask it on https://github.com/nvim-tree/nvim-tree.lua/discussions
This plugin doesn't change nvim-tree.lua core functionality(create, delete, move, rename etc.)

**Comment by semi710** [comment]
https://github.com/nvim-tree/nvim-tree.lua/issues/2743

This is resolved.
Putting the related issue link for future reference.
