### ISSUE TITLE
Colors not as expected

### ISSUE THREAD

**Issue by svanharmelen** [JMarkin/nvim-tree.lua-float-preview#19]
When showing the preview, the styling is different the (for example) the styling of a telescope floating window. the main difference seems to be the background of the borders:

Actual:
<img width="753" alt="image" src="https://github.com/JMarkin/nvim-tree.lua-float-preview/assets/4171547/67f301bf-1e14-4760-9934-9842e9280280">

Expected:
<img width="839" alt="image" src="https://github.com/JMarkin/nvim-tree.lua-float-preview/assets/4171547/d672f5e3-6e21-441d-aa1f-99bac29eacc7">

Any suggestion of how to "fix" that? Thanks!

**Comment by JMarkin** [comment]
@svanharmelen sorry I don't know how works telescope, but this plugin uses [neovim api-win_config](https://neovim.io/doc/user/api.html#api-win_config), I think section `border` can help you. 
You can modify window config in section opts.window or modify float window [globally](https://github.com/JMarkin/nvim-tree.lua-float-preview?tab=readme-ov-file#configure-window-size) `open_win_config` return arguments for api-win_config too.

**Comment by svanharmelen** [comment]
Thanks for the pointer I will have a look 👍🏻
